name: Test Build Environment

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  test_environment:
    runs-on: [self-hosted, Windows, gpu]
    steps:
      - name: Check Git
        shell: pwsh
        run: |
          Write-Host "Testing git availability..."
          git --version | Out-String -Width 4096
          
      - name: Check PowerShell Version
        shell: pwsh
        run: |
          Write-Host "PowerShell Version:"
          $PSVersionTable | Format-Table -AutoSize -Wrap | Out-String -Width 4096
          
      - name: Print Environment Variables
        shell: pwsh
        run: |
          Write-Host "Environment Variables:"
          Get-ChildItem env: | Sort-Object Name | Format-Table -AutoSize -Wrap @{
            Label = "Name"
            Expression = {$_.Name}
            Width = 40
          }, @{
            Label = "Value"
            Expression = {$_.Value}
            Width = 100
          } | Out-String -Width 8192
          
      - name: Test Required Tools
        shell: pwsh
        run: |
          $results = @()
          $tools = @(
            "python --version",
            "node --version",
            "npm --version",
            "git --version"
          )
          
          foreach ($cmd in $tools) {
            Write-Host "Testing: $cmd" -NoNewline
            try {
              $output = (Invoke-Expression $cmd) 2>&1 | Out-String
              $results += [PSCustomObject]@{
                Tool = $cmd
                Status = "✅ Available"
                Version = $output.Trim()
              }
            } catch {
              $results += [PSCustomObject]@{
                Tool = $cmd
                Status = "❌ Failed"
                Version = $_.Exception.Message
              }
            }
          }
          
          $results | Format-Table -AutoSize -Wrap | Out-String -Width 4096
